### ISSUE TITLE
unstable rust features in code?

### ISSUE THREAD

**Issue by felixhekhorn** [N3PDF/pineappl#158]
In https://github.com/N3PDF/pineappl/commit/f4f47f63e7118eb43479be8b3eec8fa5b53fc1fa I changed some string outputs - and so I had to also adjust the tests, which I hope I did - but I cannot test it because I get
```
$ cargo test
   Compiling pineappl v0.5.4 (/home/felix/Physik/N3PDF/PineAPPL/pineappl/pineappl)
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
   --> pineappl/src/sparse_array3.rs:244:6
    |
244 | impl<T: Clone + Default + PartialEq> SparseArray3<T> {
    |      ^
...
322 |     pub const fn dimensions(&self) -> (usize, usize, usize) {
    |     ------------------------------------------------------- function declared as const here
    |
    = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `pineappl` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```
the mentioned command says something that I have to activate nightly to use unstable features - which is not what I want and moreover PineAPPL is supposed to work with 1.56.1

just for reference
```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/felix/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

however, I was able to install the CLI (whose installation instructions [I updated](https://github.com/N3PDF/pineappl/commit/42d5dc7e62f440abdc8149cec84124aaa9762318) as well by the way)

**Comment by AleCandido** [comment]
I guess it has been solved in [Rust 1.61.0](https://github.com/rust-lang/rust/blob/master/RELEASES.md#language-1):

> [`const fn` signatures can now use `impl Trait` in argument and return position](https://github.com/rust-lang/rust/pull/93827/)

And since now Rust 1.62 is stable, I guess there is no problem.

**Comment by felixhekhorn** [comment]
no problem - as long as we change https://github.com/N3PDF/pineappl/blob/f4f47f63e7118eb43479be8b3eec8fa5b53fc1fa/docs/installation.md#L122

**Comment by AleCandido** [comment]
> no problem - as long as we change

Perfectly fine by me, I'd simply replace `1.56.1` by `stable`, and we'll always make sure it is going to work on stable. What do you think @cschwan?

**Comment by cschwan** [comment]
I'd like to avoid changing the MSRV since I know a few people like to use Rust from their Linux distribution. Commit 6c2b1aca7bb5e2dc391aae4eafd04a5fa53a29de should fix the problem. Please re-open if that isn't the case!

**Comment by felixhekhorn** [comment]
`cargo test` passed :+1:  (after I remembered to run `cargo build` first - it is quite strange `test` is not running it on it's own ... )

**Comment by cschwan** [comment]
`cargo test` can take quite long to finish which is why it doesn't run by default.
